name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller main.spec

      - name: Create installer
        run: |
          mkdir output
          Copy-Item -Path .\BruckerCoSetupInstaller.exe -Destination dist\pdf_tool
          .\create_installer.ps1 -SourceDir "dist\pdf_tool" -OutputDir "output" -InstallerScript ".\script.bcs"
        shell: powershell

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: PDF_Tool_Installer
          path: output\pdf_tool_installer.exe
